### ISSUE TITLE
Adding custom rocket and engine configuration

### ISSUE THREAD

**Issue by thevoxium** [thevoxium/NOVA#10]
In the main.cpp file, we are defining properties for rocket and propulsion system. It is hardcoded right now; a person will have to change the main.cpp again and again to run the simulation properly. This is tedious. Need to come up with a way to get custom configuration. There are many options like command line arguments, or a config file (in JSON format). For the config file, you will have to add a JSON parsing library.

**Comment by productsystem** [comment]
https://github.com/thevoxium/NOVA/pull/15

my attempt

**Comment by productsystem** [comment]
https://github.com/thevoxium/NOVA/pull/18

made changes as per the mail given

**Comment by thevoxium** [comment]
closing, solved with #18
