### ISSUE TITLE
Adding Rocket Crash Status Message based on altitude

### ISSUE THREAD

**Issue by thevoxium** [thevoxium/NOVA#3]
Right now if the rocket's altitude becomes negative, it keeps on running the simulation. Need to fix it such that when it becomes 0, the simulation should stop and the display should say the rocket has crashed in the mission status.

**Comment by LaurensdeGraaff** [comment]
On it

Forked the repo and added some code for crash detection.
Will test sometime later and PR if good

Is it okay for me to add a devcontainer to this repo?

**Comment by LaurensdeGraaff** [comment]
Was bored, see PR #4

**Comment by thevoxium** [comment]
Marking as closed.
